In [3]:
import numpy as np

# Array creation functions

In [4]:
# Create an array from a list

mylist=[1,2,3,4,5,6,7,8,9,10]
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
a=np.array(mylist)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a=np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [7]:
#Create an array with evenly spaced value
b=np.arange(0,10,2)              # Values from 0 to 10 with 2 steps
print("Array:",b)

Array: [0 2 4 6 8]


In [8]:
#Create an array filled with zero

b=np.zeros([2,3],dtype=int)                            #2x3 arrays of zeros
b

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
#Create an array filled with Ones
c=np.ones([2,3],dtype=int)                                  #2x3 arrays of Ones
c

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
#Create an identity matrix
d=np.eye(4)      #4x4 identity matrix
print("Identity Mtrix d:\n", d)


Identity Mtrix d:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array manipulation functions

In [11]:
# Reshaped an array

a1=np.array([1,2,3])
reshaped=np.reshape(a1,(3,1))
print("Reshaped Array: ",reshaped)

Reshaped Array:  [[1]
 [2]
 [3]]


In [12]:
# Reshaped an array

a1=np.array([1,2,3,4,5,6])
reshaped=np.reshape(a1,(3,2))
print("Reshaped Array:",reshaped)

Reshaped Array: [[1 2]
 [3 4]
 [5 6]]


In [13]:
# Flattern an array
f2=np.array([[1,2],[5,6]])
flattened=np.ravel(f2)
print("Flattened array :",flattened)

Flattened array : [1 2 5 6]


In [14]:
f1=np.array([[1,2],[3,4],[5,6]])                 # To convert in 1D array
Flattened=np.ravel(f1)
print("Flattened Array:",Flattened)

Flattened Array: [1 2 3 4 5 6]


In [15]:
#Transpose and array

In [16]:
t1=np.array([[1,2],[3,4],[5,6]])
Trans=np.transpose(t1)
print("Transpose Array :\n",Trans)

Transpose Array :
 [[1 3 5]
 [2 4 6]]


In [17]:
#Stack Array horizontally

a2=np.array([1,2])
b2=np.array([3,4])

Stacked=np.hstack([a2,b2])
print("Stacked Array:\n",Stacked)

Stacked Array:
 [1 2 3 4]


# Mathematical Function

In [22]:
#Add two arrays

g=np.array([1,2,3,4])
added=np.add(g,2)
print("added 2 to g:",added)                 #1+2 / 2+2 / 3+2 / 4+2

added 2 to g: [3 4 5 6]


In [24]:
#Square each element

g=np.array([1,2,3,4])
Squared=np.power(g,2)
print("Squared :",Squared)                   # 1x1=1 , 2x2=4 , 3x3=9 , 4x4=16

Squared : [ 1  4  9 16]


In [26]:
#Square root of each element

sqrt_val1=np.sqrt(g)            # Square root of each element
print("Square root of g:",sqrt_val1)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [35]:
a3=np.array([1,2,3])
a4=np.array([4,5,6])
Dot_Product=np.dot(a3,a4)
print("Dot_Product:",Dot_Product)

Dot_Product: 32


##  Do work on  ------ 12 T13- NUMPY Complete Documentatin