What is Numpy? 
NumPy is the fundamental package for scientific computing in Python. 

It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. 
At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types 


In [108]:
import numpy as np
import matplotlib.pyplot as plt
np.version

<module 'numpy.version' from 'C:\\Users\\dravi\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>

In [68]:
np.__version__

'2.3.5'

# Creating Numpy array 

In [69]:
np.array([2,4,6,8,10])                                            # 1D Array

array([ 2,  4,  6,  8, 10])

In [70]:
mylist=[2,4,6,8,10,12,14,16,18,20]                        # Vector
arr=np.array(mylist)

In [71]:
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [72]:
print(type(arr))

<class 'numpy.ndarray'>


In [73]:
TwoD=np.array([[2,3,4,5],[6,7,8,9]])                                  #2D Array  (Matrix)
print(TwoD)

[[2 3 4 5]
 [6 7 8 9]]


In [74]:
ThreeD=np.array([[2,3,4,5],[6,7,8,9],[10,11,12,13],[14,15,16,17]])                   #3D array (Tensor)
print(ThreeD)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


In [75]:
np.arange(10)                                               #arange it will print the value within interval 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.arange(5,10)  

array([5, 6, 7, 8, 9])

In [77]:
np.arange(5,10,2)  

array([5, 7, 9])

In [78]:
np.arange(5,10,2,2)  

TypeError: Cannot interpret '2' as a data type

# Zeros

In [79]:
np.zeros(5)                                                #parameter tunning 

array([0., 0., 0., 0., 0.])

In [80]:
np.zeros(5, dtype=int)                                        #hyperparameter tunning 

array([0, 0, 0, 0, 0])

In [81]:
np.zeros([2,2],dtype=int)                           # [2,2] 2 rows and 2 Colums

array([[0, 0],
       [0, 0]])

In [82]:
np.zeros([2,2])   

array([[0., 0.],
       [0., 0.]])

In [83]:
np.zeros([5,5],dtype=int)    

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [84]:
np.zeros([5,5])    

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Ones

In [85]:
np.ones(1)

array([1.])

In [86]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [87]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [88]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [89]:
np.ones([5,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Random

In [90]:
np.random.rand(5)

array([0.16401132, 0.19518487, 0.24715484, 0.26228055, 0.53342532])

In [91]:
np.random.rand(1)

array([0.20821196])

In [92]:
np.random.rand(10)                                          # Will give output of random float values from 0 to 10

array([0.27986543, 0.91734654, 0.11475555, 0.46674096, 0.37328973,
       0.03930044, 0.39004581, 0.87240294, 0.2776132 , 0.90714605])

In [93]:
np.random.rand(1,10)

array([[0.35825229, 0.10320113, 0.97108681, 0.44087765, 0.95340727,
        0.65988555, 0.32832425, 0.2217394 , 0.43501502, 0.29567843]])

In [94]:
np.random.randint(10)                                              # Will give output of any random value

4

In [95]:
np.random.randint(1,10)      

9

In [96]:
np.random.randint(1,10)    

9

In [97]:
np.random.randint(1,10)    

8

In [111]:
otp = np.random.randint(5,10,4)
print(otp)

[7 9 5 9]


In [112]:
otp

array([7, 9, 5, 9], dtype=int32)

In [113]:
otp = np.random.randint(5,10,4)
print(otp)

[5 5 8 9]


In [121]:
arr1=np.random.randint(10,50,(10,10))
print(arr1)

[[34 15 38 30 40 10 30 47 30 35]
 [45 38 18 43 48 35 47 32 22 46]
 [26 36 45 26 26 11 22 10 15 16]
 [37 24 47 44 42 38 44 35 39 36]
 [24 19 33 11 25 33 43 23 35 39]
 [15 33 18 28 12 17 36 25 20 22]
 [37 38 14 10 31 27 24 15 21 39]
 [24 27 46 24 43 12 47 30 13 15]
 [44 23 26 36 25 11 40 26 30 37]
 [25 15 20 29 27 38 27 46 47 46]]


# Indexing Slicing & Array

In [122]:
arr1

array([[34, 15, 38, 30, 40, 10, 30, 47, 30, 35],
       [45, 38, 18, 43, 48, 35, 47, 32, 22, 46],
       [26, 36, 45, 26, 26, 11, 22, 10, 15, 16],
       [37, 24, 47, 44, 42, 38, 44, 35, 39, 36],
       [24, 19, 33, 11, 25, 33, 43, 23, 35, 39],
       [15, 33, 18, 28, 12, 17, 36, 25, 20, 22],
       [37, 38, 14, 10, 31, 27, 24, 15, 21, 39],
       [24, 27, 46, 24, 43, 12, 47, 30, 13, 15],
       [44, 23, 26, 36, 25, 11, 40, 26, 30, 37],
       [25, 15, 20, 29, 27, 38, 27, 46, 47, 46]], dtype=int32)

In [123]:
arr1[:]

array([[34, 15, 38, 30, 40, 10, 30, 47, 30, 35],
       [45, 38, 18, 43, 48, 35, 47, 32, 22, 46],
       [26, 36, 45, 26, 26, 11, 22, 10, 15, 16],
       [37, 24, 47, 44, 42, 38, 44, 35, 39, 36],
       [24, 19, 33, 11, 25, 33, 43, 23, 35, 39],
       [15, 33, 18, 28, 12, 17, 36, 25, 20, 22],
       [37, 38, 14, 10, 31, 27, 24, 15, 21, 39],
       [24, 27, 46, 24, 43, 12, 47, 30, 13, 15],
       [44, 23, 26, 36, 25, 11, 40, 26, 30, 37],
       [25, 15, 20, 29, 27, 38, 27, 46, 47, 46]], dtype=int32)

In [125]:
arr1[::1]

array([[34, 15, 38, 30, 40, 10, 30, 47, 30, 35],
       [45, 38, 18, 43, 48, 35, 47, 32, 22, 46],
       [26, 36, 45, 26, 26, 11, 22, 10, 15, 16],
       [37, 24, 47, 44, 42, 38, 44, 35, 39, 36],
       [24, 19, 33, 11, 25, 33, 43, 23, 35, 39],
       [15, 33, 18, 28, 12, 17, 36, 25, 20, 22],
       [37, 38, 14, 10, 31, 27, 24, 15, 21, 39],
       [24, 27, 46, 24, 43, 12, 47, 30, 13, 15],
       [44, 23, 26, 36, 25, 11, 40, 26, 30, 37],
       [25, 15, 20, 29, 27, 38, 27, 46, 47, 46]], dtype=int32)

In [126]:
arr1[::-1]

array([[25, 15, 20, 29, 27, 38, 27, 46, 47, 46],
       [44, 23, 26, 36, 25, 11, 40, 26, 30, 37],
       [24, 27, 46, 24, 43, 12, 47, 30, 13, 15],
       [37, 38, 14, 10, 31, 27, 24, 15, 21, 39],
       [15, 33, 18, 28, 12, 17, 36, 25, 20, 22],
       [24, 19, 33, 11, 25, 33, 43, 23, 35, 39],
       [37, 24, 47, 44, 42, 38, 44, 35, 39, 36],
       [26, 36, 45, 26, 26, 11, 22, 10, 15, 16],
       [45, 38, 18, 43, 48, 35, 47, 32, 22, 46],
       [34, 15, 38, 30, 40, 10, 30, 47, 30, 35]], dtype=int32)

In [129]:
arr1

array([[34, 15, 38, 30, 40, 10, 30, 47, 30, 35],
       [45, 38, 18, 43, 48, 35, 47, 32, 22, 46],
       [26, 36, 45, 26, 26, 11, 22, 10, 15, 16],
       [37, 24, 47, 44, 42, 38, 44, 35, 39, 36],
       [24, 19, 33, 11, 25, 33, 43, 23, 35, 39],
       [15, 33, 18, 28, 12, 17, 36, 25, 20, 22],
       [37, 38, 14, 10, 31, 27, 24, 15, 21, 39],
       [24, 27, 46, 24, 43, 12, 47, 30, 13, 15],
       [44, 23, 26, 36, 25, 11, 40, 26, 30, 37],
       [25, 15, 20, 29, 27, 38, 27, 46, 47, 46]], dtype=int32)

In [130]:
arr1[1,1]                                                        # row number 1   / # Colum Number 1

np.int32(38)

In [134]:
arr1.shape

(10, 10)

In [135]:
len(arr1)

10

In [136]:
arr1[0]

array([34, 15, 38, 30, 40, 10, 30, 47, 30, 35], dtype=int32)

In [137]:
arr1[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [138]:
arr1[9]

array([25, 15, 20, 29, 27, 38, 27, 46, 47, 46], dtype=int32)

In [139]:
arr1

array([[34, 15, 38, 30, 40, 10, 30, 47, 30, 35],
       [45, 38, 18, 43, 48, 35, 47, 32, 22, 46],
       [26, 36, 45, 26, 26, 11, 22, 10, 15, 16],
       [37, 24, 47, 44, 42, 38, 44, 35, 39, 36],
       [24, 19, 33, 11, 25, 33, 43, 23, 35, 39],
       [15, 33, 18, 28, 12, 17, 36, 25, 20, 22],
       [37, 38, 14, 10, 31, 27, 24, 15, 21, 39],
       [24, 27, 46, 24, 43, 12, 47, 30, 13, 15],
       [44, 23, 26, 36, 25, 11, 40, 26, 30, 37],
       [25, 15, 20, 29, 27, 38, 27, 46, 47, 46]], dtype=int32)

In [141]:
arr1[:1]

array([[34, 15, 38, 30, 40, 10, 30, 47, 30, 35]], dtype=int32)

In [142]:
arr1[1:]

array([[45, 38, 18, 43, 48, 35, 47, 32, 22, 46],
       [26, 36, 45, 26, 26, 11, 22, 10, 15, 16],
       [37, 24, 47, 44, 42, 38, 44, 35, 39, 36],
       [24, 19, 33, 11, 25, 33, 43, 23, 35, 39],
       [15, 33, 18, 28, 12, 17, 36, 25, 20, 22],
       [37, 38, 14, 10, 31, 27, 24, 15, 21, 39],
       [24, 27, 46, 24, 43, 12, 47, 30, 13, 15],
       [44, 23, 26, 36, 25, 11, 40, 26, 30, 37],
       [25, 15, 20, 29, 27, 38, 27, 46, 47, 46]], dtype=int32)

In [143]:
arr1[::1]

array([[34, 15, 38, 30, 40, 10, 30, 47, 30, 35],
       [45, 38, 18, 43, 48, 35, 47, 32, 22, 46],
       [26, 36, 45, 26, 26, 11, 22, 10, 15, 16],
       [37, 24, 47, 44, 42, 38, 44, 35, 39, 36],
       [24, 19, 33, 11, 25, 33, 43, 23, 35, 39],
       [15, 33, 18, 28, 12, 17, 36, 25, 20, 22],
       [37, 38, 14, 10, 31, 27, 24, 15, 21, 39],
       [24, 27, 46, 24, 43, 12, 47, 30, 13, 15],
       [44, 23, 26, 36, 25, 11, 40, 26, 30, 37],
       [25, 15, 20, 29, 27, 38, 27, 46, 47, 46]], dtype=int32)

In [145]:
arr1

array([[34, 15, 38, 30, 40, 10, 30, 47, 30, 35],
       [45, 38, 18, 43, 48, 35, 47, 32, 22, 46],
       [26, 36, 45, 26, 26, 11, 22, 10, 15, 16],
       [37, 24, 47, 44, 42, 38, 44, 35, 39, 36],
       [24, 19, 33, 11, 25, 33, 43, 23, 35, 39],
       [15, 33, 18, 28, 12, 17, 36, 25, 20, 22],
       [37, 38, 14, 10, 31, 27, 24, 15, 21, 39],
       [24, 27, 46, 24, 43, 12, 47, 30, 13, 15],
       [44, 23, 26, 36, 25, 11, 40, 26, 30, 37],
       [25, 15, 20, 29, 27, 38, 27, 46, 47, 46]], dtype=int32)

In [146]:
arr1[-1::]

array([[25, 15, 20, 29, 27, 38, 27, 46, 47, 46]], dtype=int32)

In [147]:
arr1[::-1]

array([[25, 15, 20, 29, 27, 38, 27, 46, 47, 46],
       [44, 23, 26, 36, 25, 11, 40, 26, 30, 37],
       [24, 27, 46, 24, 43, 12, 47, 30, 13, 15],
       [37, 38, 14, 10, 31, 27, 24, 15, 21, 39],
       [15, 33, 18, 28, 12, 17, 36, 25, 20, 22],
       [24, 19, 33, 11, 25, 33, 43, 23, 35, 39],
       [37, 24, 47, 44, 42, 38, 44, 35, 39, 36],
       [26, 36, 45, 26, 26, 11, 22, 10, 15, 16],
       [45, 38, 18, 43, 48, 35, 47, 32, 22, 46],
       [34, 15, 38, 30, 40, 10, 30, 47, 30, 35]], dtype=int32)

In [152]:
arr1

array([[34, 15, 38, 30, 40, 10, 30, 47, 30, 35],
       [45, 38, 18, 43, 48, 35, 47, 32, 22, 46],
       [26, 36, 45, 26, 26, 11, 22, 10, 15, 16],
       [37, 24, 47, 44, 42, 38, 44, 35, 39, 36],
       [24, 19, 33, 11, 25, 33, 43, 23, 35, 39],
       [15, 33, 18, 28, 12, 17, 36, 25, 20, 22],
       [37, 38, 14, 10, 31, 27, 24, 15, 21, 39],
       [24, 27, 46, 24, 43, 12, 47, 30, 13, 15],
       [44, 23, 26, 36, 25, 11, 40, 26, 30, 37],
       [25, 15, 20, 29, 27, 38, 27, 46, 47, 46]], dtype=int32)

In [153]:
arr1[:,0]                                                        # To print colum

array([34, 45, 26, 37, 24, 15, 37, 24, 44, 25], dtype=int32)

In [154]:
arr1[:,1]

array([15, 38, 36, 24, 19, 33, 38, 27, 23, 15], dtype=int32)

In [155]:
arr1[:,2]

array([38, 18, 45, 47, 33, 18, 14, 46, 26, 20], dtype=int32)

In [156]:
arr1

array([[34, 15, 38, 30, 40, 10, 30, 47, 30, 35],
       [45, 38, 18, 43, 48, 35, 47, 32, 22, 46],
       [26, 36, 45, 26, 26, 11, 22, 10, 15, 16],
       [37, 24, 47, 44, 42, 38, 44, 35, 39, 36],
       [24, 19, 33, 11, 25, 33, 43, 23, 35, 39],
       [15, 33, 18, 28, 12, 17, 36, 25, 20, 22],
       [37, 38, 14, 10, 31, 27, 24, 15, 21, 39],
       [24, 27, 46, 24, 43, 12, 47, 30, 13, 15],
       [44, 23, 26, 36, 25, 11, 40, 26, 30, 37],
       [25, 15, 20, 29, 27, 38, 27, 46, 47, 46]], dtype=int32)

In [158]:
arr1[3:4, 2:6]

array([[47, 44, 42, 38]], dtype=int32)

In [159]:
arr1[1:4, 1:6]

array([[38, 18, 43, 48, 35],
       [36, 45, 26, 26, 11],
       [24, 47, 44, 42, 38]], dtype=int32)

#  1. Arange

In [191]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [192]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [193]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [194]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [197]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [207]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [209]:
a=np.arange(1,17).reshape(4,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [210]:
print(type(a))

<class 'numpy.ndarray'>


# 2️⃣ Check Shape & Type

In [163]:
arr1

array([[34, 15, 38, 30, 40, 10, 30, 47, 30, 35],
       [45, 38, 18, 43, 48, 35, 47, 32, 22, 46],
       [26, 36, 45, 26, 26, 11, 22, 10, 15, 16],
       [37, 24, 47, 44, 42, 38, 44, 35, 39, 36],
       [24, 19, 33, 11, 25, 33, 43, 23, 35, 39],
       [15, 33, 18, 28, 12, 17, 36, 25, 20, 22],
       [37, 38, 14, 10, 31, 27, 24, 15, 21, 39],
       [24, 27, 46, 24, 43, 12, 47, 30, 13, 15],
       [44, 23, 26, 36, 25, 11, 40, 26, 30, 37],
       [25, 15, 20, 29, 27, 38, 27, 46, 47, 46]], dtype=int32)

In [160]:
arr1.shape

(10, 10)

In [161]:
arr1.ndim

2

In [162]:
arr1.dtype

dtype('int32')

# 3️⃣ 2D Array (Matrix)

In [165]:
np.array([[2,2],[1,4]])

array([[2, 2],
       [1, 4]])

# 4️⃣ Special Arrays (Very Important)

In [166]:
np.zeros(1)

array([0.])

In [167]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [168]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [169]:
np.zeros([5,5],dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [170]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [171]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [172]:
np.ones([5,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [173]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [176]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [175]:
np.eye([5,5],dtype=int)

TypeError: 'list' object cannot be interpreted as an integer

# 5️⃣ Random Arrays

In [177]:
np.random.rand(1)

array([0.26268915])

In [178]:
np.random.rand(5)

array([0.26894117, 0.76777113, 0.5350231 , 0.08776856, 0.71367963])

In [179]:
np.random.rand(10)

array([0.80556883, 0.31834181, 0.6521886 , 0.46404273, 0.16885677,
       0.74778274, 0.92288853, 0.51154243, 0.86138712, 0.59922305])

In [181]:
np.random.rand(10,50,(10,10))

TypeError: 'tuple' object cannot be interpreted as an integer

In [182]:
np.random.rand(10,10)

array([[0.48626511, 0.0354582 , 0.00564878, 0.00278828, 0.41397782,
        0.54857438, 0.39242209, 0.69263759, 0.16533172, 0.77716536],
       [0.17408056, 0.78734826, 0.04868594, 0.37608526, 0.13677536,
        0.17538689, 0.46621703, 0.86514233, 0.87191362, 0.46186061],
       [0.33132794, 0.98601323, 0.73103333, 0.41358199, 0.79791959,
        0.36695554, 0.02588382, 0.02769368, 0.7634308 , 0.76709106],
       [0.83569713, 0.3791143 , 0.13152045, 0.39200585, 0.84543355,
        0.84941041, 0.36900586, 0.89220536, 0.20973742, 0.44703172],
       [0.63416786, 0.21606285, 0.9781318 , 0.91869066, 0.66284781,
        0.71739286, 0.08884057, 0.50695498, 0.8362165 , 0.05274732],
       [0.89482964, 0.36128561, 0.20958866, 0.12373222, 0.24139015,
        0.30798272, 0.36263936, 0.51647021, 0.83454112, 0.61563242],
       [0.01089939, 0.2119759 , 0.63500464, 0.32672408, 0.93406534,
        0.96726746, 0.60299717, 0.25329786, 0.62691893, 0.67325219],
       [0.99991212, 0.84894045, 0.8152271

In [183]:
np.random.randint(10)

9

In [185]:
np.random.randint(10,50,[10,10])

array([[24, 45, 10, 32, 37, 45, 40, 20, 36, 37],
       [12, 19, 25, 21, 44, 34, 39, 43, 42, 30],
       [45, 49, 48, 44, 45, 38, 37, 43, 25, 14],
       [16, 27, 16, 38, 17, 14, 24, 41, 35, 41],
       [31, 28, 21, 34, 19, 37, 45, 38, 36, 42],
       [14, 31, 33, 18, 19, 24, 33, 11, 27, 10],
       [19, 38, 18, 23, 26, 34, 30, 31, 45, 39],
       [17, 44, 24, 28, 37, 31, 38, 12, 31, 40],
       [40, 38, 30, 19, 41, 25, 30, 26, 28, 41],
       [49, 10, 42, 49, 13, 48, 41, 22, 15, 44]], dtype=int32)

In [189]:
otp=np.random.randint(2,10,4)
print(otp)

[3 4 6 4]


# 6️⃣ Indexing & Slicing

In [190]:
arr1

array([[34, 15, 38, 30, 40, 10, 30, 47, 30, 35],
       [45, 38, 18, 43, 48, 35, 47, 32, 22, 46],
       [26, 36, 45, 26, 26, 11, 22, 10, 15, 16],
       [37, 24, 47, 44, 42, 38, 44, 35, 39, 36],
       [24, 19, 33, 11, 25, 33, 43, 23, 35, 39],
       [15, 33, 18, 28, 12, 17, 36, 25, 20, 22],
       [37, 38, 14, 10, 31, 27, 24, 15, 21, 39],
       [24, 27, 46, 24, 43, 12, 47, 30, 13, 15],
       [44, 23, 26, 36, 25, 11, 40, 26, 30, 37],
       [25, 15, 20, 29, 27, 38, 27, 46, 47, 46]], dtype=int32)

In [213]:
arr1[0]

array([34, 15, 38, 30, 40, 10, 30, 47, 30, 35], dtype=int32)

In [214]:
arr1[1]

array([45, 38, 18, 43, 48, 35, 47, 32, 22, 46], dtype=int32)

In [215]:
arr1[2]

array([26, 36, 45, 26, 26, 11, 22, 10, 15, 16], dtype=int32)

In [216]:
arr1[3]

array([37, 24, 47, 44, 42, 38, 44, 35, 39, 36], dtype=int32)

In [217]:
arr1[:,0]

array([34, 45, 26, 37, 24, 15, 37, 24, 44, 25], dtype=int32)

In [218]:
arr1[:,1]

array([15, 38, 36, 24, 19, 33, 38, 27, 23, 15], dtype=int32)

In [219]:
arr1[:,2]

array([38, 18, 45, 47, 33, 18, 14, 46, 26, 20], dtype=int32)

In [220]:
arr1[:,3]

array([30, 43, 26, 44, 11, 28, 10, 24, 36, 29], dtype=int32)

In [221]:
arr1

array([[34, 15, 38, 30, 40, 10, 30, 47, 30, 35],
       [45, 38, 18, 43, 48, 35, 47, 32, 22, 46],
       [26, 36, 45, 26, 26, 11, 22, 10, 15, 16],
       [37, 24, 47, 44, 42, 38, 44, 35, 39, 36],
       [24, 19, 33, 11, 25, 33, 43, 23, 35, 39],
       [15, 33, 18, 28, 12, 17, 36, 25, 20, 22],
       [37, 38, 14, 10, 31, 27, 24, 15, 21, 39],
       [24, 27, 46, 24, 43, 12, 47, 30, 13, 15],
       [44, 23, 26, 36, 25, 11, 40, 26, 30, 37],
       [25, 15, 20, 29, 27, 38, 27, 46, 47, 46]], dtype=int32)

In [226]:
arr1[1,1]                   # 1 row and 1 colum value according to index

np.int32(38)

In [235]:
b=np.random.randint(1,10,[3,3])

In [236]:
b

array([[9, 5, 6],
       [8, 8, 1],
       [2, 5, 1]], dtype=int32)

In [237]:
b[0]                                             # 0 Row → horizontal

array([9, 5, 6], dtype=int32)

In [238]:
b[1]                                            # 1st Row → horizontal

array([8, 8, 1], dtype=int32)

In [239]:
b[2]                                            # 2nd Row → horizontal

array([2, 5, 1], dtype=int32)

In [240]:
b[:,0]                                                              # 0 Column → vertical

array([9, 8, 2], dtype=int32)

In [241]:
b[:,1]                                                              # 1st Column → vertical

array([5, 8, 5], dtype=int32)

In [242]:
b[:,2]                                                              # 2nd Column → vertical

array([6, 1, 1], dtype=int32)

In [246]:
b

array([[9, 5, 6],
       [8, 8, 1],
       [2, 5, 1]], dtype=int32)

In [245]:
b[:1]

array([[9, 5, 6]], dtype=int32)

In [248]:
b[:2]

array([[9, 5, 6],
       [8, 8, 1]], dtype=int32)

In [249]:
b[:3]

array([[9, 5, 6],
       [8, 8, 1],
       [2, 5, 1]], dtype=int32)

In [253]:
b

array([[9, 5, 6],
       [8, 8, 1],
       [2, 5, 1]], dtype=int32)

In [254]:
b[0:]

array([[9, 5, 6],
       [8, 8, 1],
       [2, 5, 1]], dtype=int32)

In [255]:
b[1:]

array([[8, 8, 1],
       [2, 5, 1]], dtype=int32)

In [257]:
b[2:]

array([[2, 5, 1]], dtype=int32)

In [258]:
b

array([[9, 5, 6],
       [8, 8, 1],
       [2, 5, 1]], dtype=int32)

In [262]:
b[1,2]

np.int32(1)

In [263]:
b[2,2]

np.int32(1)

In [265]:
b

array([[9, 5, 6],
       [8, 8, 1],
       [2, 5, 1]], dtype=int32)

In [264]:
b[-1]

array([2, 5, 1], dtype=int32)

In [266]:
b[::-1]

array([[2, 5, 1],
       [8, 8, 1],
       [9, 5, 6]], dtype=int32)

In [267]:
b[:-2]

array([[9, 5, 6]], dtype=int32)